"""Telegram bot factory + lifecycle delegates.

This is the top-level wiring point for the PTB ``Application``. The
actual handler bodies live in feature subpackages under ``handlers/``;
``register_all`` composes them into the application, and ``bootstrap``
runs the post-init / post-shutdown sequence.

Responsibilities kept here:
  - ``create_bot`` — PTB ``Application.builder()`` factory
  - lifecycle delegates: ``post_init``, ``post_stop``, ``post_shutdown``
  - ``_error_handler`` — top-level error funnel for the application
  - ``_send_shutdown_notification`` — best-effort goodbye message
  - ``_group_filter`` / ``is_user_allowed`` — auth/filter helpers used
    by the message handler registry
"""

import os
import signal
import time

import structlog
from telegram.error import BadRequest, Conflict, NetworkError
from telegram.ext import (
    Application,
    ContextTypes,
    filters,
)

from . import bootstrap
from .config import config
from .handlers.inline import inline_query_handler, unsupported_content_handler
from .handlers.commands import commands_command, toolbar_command
from .handlers.messaging_pipeline import toolcalls_command, verbose_command
from .handlers.messaging_pipeline.message_sender import safe_reply
from .handlers.recovery.history import history_command
from .handlers.registry import register_all
from .handlers.text.text_handler import handle_text_message, text_handler
from .handlers.topics import new_command
from .handlers.topics.directory_browser import clear_browse_state
from .session import session_manager
from .telegram_request import ResilientPollingHTTPXRequest
from .telegram_rate_limiter import CCGramAIORateLimiter
from .thread_router import thread_router
from .update_processor import OperatorUpdateProcessor

# Re-export the moved handler callables and supporting singletons so
# existing tests and integration suites that import them from
# ``ccgram.bot`` keep working without churn. Canonical homes are the
# feature subpackages — these names are retained for ``patch`` targets.
__all__ = [
    "clear_browse_state",
    "commands_command",
    "create_bot",
    "handle_text_message",
    "history_command",
    "inline_query_handler",
    "is_user_allowed",
    "new_command",
    "post_init",
    "post_shutdown",
    "post_stop",
    "safe_reply",
    "session_manager",
    "text_handler",
    "thread_router",
    "toolbar_command",
    "toolcalls_command",
    "unsupported_content_handler",
    "verbose_command",
]

logger = structlog.get_logger()

_GET_UPDATES_READ_TIMEOUT_S = 20.0


def is_user_allowed(user_id: int | None) -> bool:
    """Thin wrapper around ``config.is_user_allowed`` for None-safety."""
    return user_id is not None and config.is_user_allowed(user_id)


# Group filter: when CCGRAM_GROUP_ID is set, only process updates from that group.
# filters.ALL is a no-op — single-instance backward compat.
_group_filter: filters.BaseFilter = (
    filters.Chat(chat_id=config.group_id) if config.group_id else filters.ALL
)


# --- App lifecycle ---


async def post_init(application: Application) -> None:
    """Run the post_init wiring sequence — see ``bootstrap.bootstrap_application``."""
    await bootstrap.bootstrap_application(application)


async def _send_shutdown_notification(application: Application) -> None:
    """Send a shutdown notification to the General topic if a group is configured."""
    # Lazy: main imports bot at top to wire post_init/post_shutdown; hoisting
    # these forms a main ↔ bot cycle on cold import.
    # Lazy: bot ↔ main cycle
    from .main import _shutdown_signal

    if not config.group_id:
        return

    sig = _shutdown_signal
    reason = f"Received {signal.Signals(sig).name}" if sig else "Clean exit"

    # Lazy: __version__ is generated by hatch-vcs and only needed for the
    # shutdown banner; defer to avoid pulling it in the cold-start path.
    # Lazy: defer until startup banner runs
    from . import __version__

    # Lazy: only used inside the error handler
    from telegram.error import TelegramError

    text = f"🔌 ccgram stopped — {reason} (v{__version__})"
    try:
        await application.bot.send_message(
            chat_id=config.group_id,
            text=text,
            message_thread_id=1,  # General topic
        )
    except (TelegramError, RuntimeError) as exc:
        logger.debug("Shutdown notification skipped: %s", exc)


async def post_stop(application: Application) -> None:
    """Send shutdown notification while HTTP transport is still alive."""
    # Lazy: avoid importing the optional debounce runtime during bot construction.
    from .message_coalescer import message_coalescer

    await message_coalescer.flush_all()
    await _send_shutdown_notification(application)


async def post_shutdown(_application: Application) -> None:
    """Tear down runtime state — see ``bootstrap.shutdown_runtime``."""
    await bootstrap.shutdown_runtime()


# A restart overlaps: the outgoing process may still be draining `getUpdates`
# while the new one starts polling, which makes PTB raise `Conflict` for a few
# seconds. Shutting down on the first one killed healthy bots (and, when the
# survivor was the one exiting, left no bot at all). Only a conflict that keeps
# firing past the grace window is a real second instance.
CONFLICT_GRACE_SECONDS = 30.0
CONFLICT_MIN_COUNT = 3
# Conflicts spaced further apart than this belong to separate episodes.
CONFLICT_EPISODE_GAP = 120.0

_conflict_first_ts: float | None = None
_conflict_last_ts: float = 0.0
_conflict_count = 0


def _handle_conflict() -> None:
    """Shut down only on a sustained getUpdates conflict, not a transient one."""
    global _conflict_first_ts, _conflict_last_ts, _conflict_count
    now = time.monotonic()
    if _conflict_first_ts is None or now - _conflict_last_ts > CONFLICT_EPISODE_GAP:
        _conflict_first_ts = now
        _conflict_count = 0
    _conflict_last_ts = now
    _conflict_count += 1

    elapsed = now - _conflict_first_ts
    if elapsed < CONFLICT_GRACE_SECONDS or _conflict_count < CONFLICT_MIN_COUNT:
        logger.warning(
            "getUpdates conflict — tolerating (likely a restart overlap)",
            count=_conflict_count,
            elapsed=round(elapsed, 1),
        )
        return

    logger.critical(
        "Another bot instance has been polling with the same token for %.0fs "
        "(%d conflicts). Shutting down to avoid conflicts.",
        elapsed,
        _conflict_count,
    )
    os.kill(os.getpid(), signal.SIGINT)


def _reset_conflict_state_for_testing() -> None:
    """Reset the conflict tracker between tests."""
    global _conflict_first_ts, _conflict_last_ts, _conflict_count
    _conflict_first_ts = None
    _conflict_last_ts = 0.0
    _conflict_count = 0


async def _error_handler(_update: object, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Handle bot-level errors from updater and handlers."""
    if isinstance(context.error, Conflict):
        _handle_conflict()
        return
    if isinstance(context.error, BadRequest) and "too old" in str(context.error):
        logger.debug("Callback query expired (query too old)")
        return
    if isinstance(context.error, NetworkError) and not isinstance(
        context.error, BadRequest
    ):
        # PTB will retry automatically — not actionable; demoted from warning.
        logger.info("Transient network error (PTB will retry): %s", context.error)
        return
    logger.error("Unhandled bot error", exc_info=context.error)


def create_bot() -> Application:
    # Suppress PTBUserWarning about JobQueue (we intentionally don't use it for core tasks)
    # Lazy: only used inside the deprecation guard
    import warnings

    warnings.filterwarnings("ignore", message=".*JobQueue.*", category=UserWarning)
    configured_updates = config.max_concurrent_updates
    max_concurrent_updates = (
        configured_updates if isinstance(configured_updates, int) else 1
    )
    application = (
        Application.builder()
        .token(config.telegram_bot_token)
        .rate_limiter(CCGramAIORateLimiter(max_retries=5))
        .request(ResilientPollingHTTPXRequest(read_timeout=10, request_name="Bot API"))
        .get_updates_request(
            ResilientPollingHTTPXRequest(
                connection_pool_size=1,
                read_timeout=_GET_UPDATES_READ_TIMEOUT_S,
                request_name="getUpdates",
            )
        )
        .concurrent_updates(OperatorUpdateProcessor(max_concurrent_updates))
        .post_init(post_init)
        .post_stop(post_stop)
        .post_shutdown(post_shutdown)
        .build()
    )

    application.add_error_handler(_error_handler)
    register_all(application, _group_filter)

    return application
